export const Adjectives = [
  {
    bisaya: "dako",
    english: "big / large",
    example_bisaya: "Dako ang balay.",
    example_english: "The house is big.",
  },
  {
    bisaya: "gamay",
    english: "small / little",
    example_bisaya: "Gamay ang bata.",
    example_english: "The child is small.",
  },
  {
    bisaya: "taas",
    english: "tall / long",
    example_bisaya: "Taas ang building.",
    example_english: "The building is tall.",
  },
  {
    bisaya: "mubo",
    english: "short / low",
    example_bisaya: "Mubo ang lamesa.",
    example_english: "The table is short.",
  },
  {
    bisaya: "bag-o",
    english: "new",
    example_bisaya: "Bag-o ang sakyanan.",
    example_english: "The car is new.",
  },
  {
    bisaya: "daan",
    english: "old",
    example_bisaya: "Daan na ang balay.",
    example_english: "The house is old.",
  },
  {
    bisaya: "maayo",
    english: "good / well",
    example_bisaya: "Maayo siya nga estudyante.",
    example_english: "She is a good student.",
  },
  {
    bisaya: "daotan",
    english: "bad",
    example_bisaya: "Daotan ang panahon karon.",
    example_english: "The weather is bad today.",
  },
  {
    bisaya: "init",
    english: "hot",
    example_bisaya: "Init ang kape.",
    example_english: "The coffee is hot.",
  },
  {
    bisaya: "bugnaw",
    english: "cold",
    example_bisaya: "Bugnaw ang tubig.",
    example_english: "The water is cold.",
  },
  {
    bisaya: "hayag",
    english: "bright / light",
    example_bisaya: "Hayag ang adlaw.",
    example_english: "The sun is bright.",
  },
  {
    bisaya: "ngitngit",
    english: "dark",
    example_bisaya: "Ngitngit ang kwarto.",
    example_english: "The room is dark.",
  },
  {
    bisaya: "nindot",
    english: "beautiful / nice",
    example_bisaya: "Nindot ang tan-awon ang dagat.",
    example_english: "The sea looks beautiful.",
  },
  {
    bisaya: "bati",
    english: "ugly / unpleasant",
    example_bisaya: "Bati ang pelikula.",
    example_english: "The movie is bad.",
  },
  {
    bisaya: "malipayon",
    english: "happy",
    example_bisaya: "Malipayon ang pamilya.",
    example_english: "The family is happy.",
  },
  {
    bisaya: "masulob-on",
    english: "sad",
    example_bisaya: "Masulob-on siya karon.",
    example_english: "He is sad today.",
  },
  {
    bisaya: "kusgan",
    english: "strong",
    example_bisaya: "Kusgan ang sundalo.",
    example_english: "The soldier is strong.",
  },
  {
    bisaya: "huyang",
    english: "weak",
    example_bisaya: "Huyang ang tigulang.",
    example_english: "The old man is weak.",
  },
  {
    bisaya: "pasalig",
    english: "reliable / trustworthy",
    example_bisaya: "Pasalig siya nga amigo.",
    example_english: "He is a trustworthy friend.",
  },
  {
    bisaya: "lain",
    english: "different / another",
    example_bisaya: "Lain ang akong gusto.",
    example_english: "I want something different.",
  },
  {
    bisaya: "pareho",
    english: "same / alike",
    example_bisaya: "Pareho sila ug sinina.",
    example_english: "They have the same clothes.",
  },
  {
    bisaya: "taas-taas",
    english: "very tall / high",
    example_bisaya: "Taas-taas ang poste.",
    example_english: "The post is very tall.",
  },
  {
    bisaya: "lapad",
    english: "wide / broad",
    example_bisaya: "Lapad ang dalan.",
    example_english: "The road is wide.",
  },
  {
    bisaya: "nipis",
    english: "thin",
    example_bisaya: "Nipis ang papel.",
    example_english: "The paper is thin.",
  },
  {
    bisaya: "baga",
    english: "thick / heavy",
    example_bisaya: "Baga ang libro.",
    example_english: "The book is thick.",
  },
  {
    bisaya: "dali",
    english: "fast / quick",
    example_bisaya: "Dali siya modagan.",
    example_english: "He runs fast.",
  },
  {
    bisaya: "hinay",
    english: "slow / gentle",
    example_bisaya: "Hinay siya molihok.",
    example_english: "She moves slowly.",
  },
  {
    bisaya: "bibo",
    english: "lively / active",
    example_bisaya: "Bibo ang party kagabii.",
    example_english: "The party last night was lively.",
  },
  {
    bisaya: "hilom",
    english: "quiet / silent",
    example_bisaya: "Hilom ang library.",
    example_english: "The library is quiet.",
  },
  {
    bisaya: "maanyag",
    english: "handsome / beautiful (people)",
    example_bisaya: "Maanyag ang dalaga.",
    example_english: "The young woman is beautiful.",
  },
  {
    bisaya: "maayong pamatasan",
    english: "well-behaved / polite",
    example_bisaya: "Maayong pamatasan ang bata.",
    example_english: "The child is polite.",
  },
  {
    bisaya: "bastos",
    english: "rude / impolite",
    example_bisaya: "Bastos siya nga tawo.",
    example_english: "He is a rude person.",
  },
  {
    bisaya: "masigla",
    english: "energetic / lively",
    example_bisaya: "Masigla ang mga estudyante sa klase.",
    example_english: "The students are energetic in class.",
  },
  {
    bisaya: "tambok",
    english: "fat / chubby",
    example_bisaya: "Tambok ang iro.",
    example_english: "The dog is fat.",
  },
  {
    bisaya: "payat",
    english: "thin / skinny",
    example_bisaya: "Payat ang bata.",
    example_english: "The child is skinny.",
  },
  {
    bisaya: "hayahay",
    english: "comfortable / relaxed",
    example_bisaya: "Hayahay ang higdaanan.",
    example_english: "The bed is comfortable.",
  },
  {
    bisaya: "gahi",
    english: "hard / firm",
    example_bisaya: "Gahi ang kahoy.",
    example_english: "The wood is hard.",
  },
  {
    bisaya: "lapok",
    english: "muddy / dirty",
    example_bisaya: "Lapok ang dalan human sa ulan.",
    example_english: "The road is muddy after the rain.",
  },
  {
    bisaya: "limpyo",
    english: "clean",
    example_bisaya: "Limpyo ang kwarto.",
    example_english: "The room is clean.",
  },
  {
    bisaya: "baho",
    english: "smelly",
    example_bisaya: "Baho ang basura.",
    example_english: "The trash smells bad.",
  },
  {
    bisaya: "humot",
    english: "fragrant / nice-smelling",
    example_bisaya: "Humot ang bulak.",
    example_english: "The flower is fragrant.",
  },
  {
    bisaya: "mahuyang",
    english: "fragile / delicate",
    example_bisaya: "Mahuyang ang baso.",
    example_english: "The glass is fragile.",
  },
  {
    bisaya: "daghan",
    english: "many / a lot",
    example_bisaya: "Daghan tawo sa merkado.",
    example_english: "There are many people in the market.",
  },
  {
    bisaya: "gamay",
    english: "few / little",
    example_bisaya: "Gamay ra ang tawo sa simbahan.",
    example_english: "There are only a few people in the church.",
  },
  {
    bisaya: "kusog",
    english: "loud / strong (force)",
    example_bisaya: "Kusog ang hangin.",
    example_english: "The wind is strong.",
  },
  {
    bisaya: "hinay-hinay",
    english: "slowly / gently",
    example_bisaya: "Hinay-hinay siya naglakaw.",
    example_english: "He walked slowly.",
  },
  {
    bisaya: "bag-o ra",
    english: "recent / newly",
    example_bisaya: "Bag-o ra siya naabot.",
    example_english: "He just arrived.",
  },
  {
    bisaya: "kaayo",
    english: "very / extremely (used for emphasis)",
    example_bisaya: "Lami kaayo ang pagkaon.",
    example_english: "The food is very delicious.",
  },
  {
    bisaya: "mahimog",
    english: "possible / doable",
    example_bisaya: "Mahimog nga ulanon karon.",
    example_english: "It is possible that it will rain today.",
  },
  {
    bisaya: "lisod",
    english: "difficult / hard",
    example_bisaya: "Lisod ang problema.",
    example_english: "The problem is difficult.",
  },
];
