export const Nouns = [
  {
    bisaya: "trabaho",
    english: "work / job",
    example_bisaya: "Daghan ko’g trabaho karon.",
    example_english: "I have a lot of work today.",
  },
  {
    bisaya: "opisina",
    english: "office",
    example_bisaya: "Naa siya sa opisina.",
    example_english: "He is at the office.",
  },
  {
    bisaya: "kwarta",
    english: "money",
    example_bisaya: "Wala koy kwarta.",
    example_english: "I don’t have money.",
  },
  {
    bisaya: "sweldo",
    english: "salary / pay",
    example_bisaya: "Dawat na nako ang akong sweldo.",
    example_english: "I already received my salary.",
  },
  {
    bisaya: "oras",
    english: "time / hour",
    example_bisaya: "Unsa na nga oras?",
    example_english: "What time is it?",
  },
  {
    bisaya: "adlaw",
    english: "day",
    example_bisaya: "Maayo ang adlaw karon.",
    example_english: "The day is good today.",
  },
  {
    bisaya: "gabi-i",
    english: "night / evening",
    example_bisaya: "Mangadto ta ug mall sa gabi-i.",
    example_english: "Let’s go to the mall tonight.",
  },
  {
    bisaya: "semana",
    english: "week",
    example_bisaya: "Pila ka semana ang proyekto?",
    example_english: "How many weeks is the project?",
  },
  {
    bisaya: "bulan",
    english: "month",
    example_bisaya: "Sunod bulan magsugod ta.",
    example_english: "Next month we will start.",
  },
  {
    bisaya: "kaugmaon",
    english: "future",
    example_bisaya: "Nagplano siya para sa kaugmaon.",
    example_english: "He is planning for the future.",
  },

  {
    bisaya: "balay",
    english: "house / home",
    example_bisaya: "Nindot ang ilang balay.",
    example_english: "Their house is nice.",
  },
  {
    bisaya: "kwarto",
    english: "room / bedroom",
    example_bisaya: "Ang akong kwarto kay limpyo.",
    example_english: "My room is clean.",
  },
  {
    bisaya: "lingkuranan",
    english: "chair / seat",
    example_bisaya: "Lingkod sa lingkuranan.",
    example_english: "Sit on the chair.",
  },
  {
    bisaya: "lamisa",
    english: "table",
    example_bisaya: "Butang ang libro sa lamisa.",
    example_english: "Put the book on the table.",
  },
  {
    bisaya: "suga",
    english: "light / lamp",
    example_bisaya: "Palonga ang suga.",
    example_english: "Turn off the light.",
  },
  {
    bisaya: "kusina",
    english: "kitchen",
    example_bisaya: "Siya naa sa kusina.",
    example_english: "She is in the kitchen.",
  },
  {
    bisaya: "banyo",
    english: "bathroom",
    example_bisaya: "Gamiton nako ang banyo.",
    example_english: "I’ll use the bathroom.",
  },
  {
    bisaya: "salog",
    english: "floor",
    example_bisaya: "Ayaw ilabay ang basura sa salog.",
    example_english: "Don’t throw trash on the floor.",
  },
  {
    bisaya: "pultahan",
    english: "door",
    example_bisaya: "Sirad-i ang pultahan.",
    example_english: "Close the door.",
  },
  {
    bisaya: "bintana",
    english: "window",
    example_bisaya: "Buksan ang bintana.",
    example_english: "Open the window.",
  },

  {
    bisaya: "kape",
    english: "coffee",
    example_bisaya: "Ganahan ko ug kape buntag.",
    example_english: "I like coffee in the morning.",
  },
  {
    bisaya: "tubig",
    english: "water",
    example_bisaya: "Palihug hatag ug tubig.",
    example_english: "Please give me some water.",
  },
  {
    bisaya: "kan-on",
    english: "cooked rice",
    example_bisaya: "Daghan kaayo’g kan-on sa plato.",
    example_english: "There is a lot of rice on the plate.",
  },
  {
    bisaya: "sud-an",
    english: "viand / main dish",
    example_bisaya: "Unsa ang sud-an nato karon?",
    example_english: "What’s our viand today?",
  },
  {
    bisaya: "pagkaon",
    english: "food",
    example_bisaya: "Daghan pagkaon sa lamesa.",
    example_english: "There’s a lot of food on the table.",
  },
  {
    bisaya: "plato",
    english: "plate",
    example_bisaya: "Kulang ang plato.",
    example_english: "The plates are not enough.",
  },
  {
    bisaya: "kutsara",
    english: "spoon",
    example_bisaya: "Gamit ug kutsara para mokaon.",
    example_english: "Use a spoon to eat.",
  },
  {
    bisaya: "tinidor",
    english: "fork",
    example_bisaya: "Asa ang tinidor?",
    example_english: "Where is the fork?",
  },
  {
    bisaya: "baso",
    english: "glass",
    example_bisaya: "Butangi ug tubig ang baso.",
    example_english: "Fill the glass with water.",
  },
  {
    bisaya: "kutsilyo",
    english: "knife",
    example_bisaya: "Gamit ug kutsilyo para motabas.",
    example_english: "Use a knife to cut.",
  },

  {
    bisaya: "kompyuter",
    english: "computer",
    example_bisaya: "Gamit siya ug kompyuter sa trabaho.",
    example_english: "He uses a computer at work.",
  },
  {
    bisaya: "selpon",
    english: "cellphone",
    example_bisaya: "Naunsa imong selpon?",
    example_english: "What happened to your cellphone?",
  },
  {
    bisaya: "keyboard",
    english: "keyboard",
    example_bisaya: "Naguba ang keyboard.",
    example_english: "The keyboard is broken.",
  },
  {
    bisaya: "mouse",
    english: "mouse",
    example_bisaya: "Wala koy mouse.",
    example_english: "I don’t have a mouse.",
  },
  {
    bisaya: "internet",
    english: "internet",
    example_bisaya: "Walay internet sa opisina.",
    example_english: "There is no internet in the office.",
  },
  {
    bisaya: "mensahi",
    english: "message",
    example_bisaya: "Nadawat nako ang imong mensahi.",
    example_english: "I received your message.",
  },
  {
    bisaya: "trabahoan",
    english: "workplace",
    example_bisaya: "Layo ang iyang trabahoan.",
    example_english: "His workplace is far.",
  },
  {
    bisaya: "pulungan",
    english: "meeting / gathering",
    example_bisaya: "Naa tay pulungan ugma.",
    example_english: "We have a meeting tomorrow.",
  },
  {
    bisaya: "kolig", // alt: "kauban sa trabaho"
    english: "colleague",
    example_bisaya: "Ang akong kolig maayo ug tabang.",
    example_english: "My colleague is helpful.",
  },
  {
    bisaya: "kliyente",
    english: "client",
    example_bisaya: "Naghulat ang kliyente.",
    example_english: "The client is waiting.",
  },

  {
    bisaya: "lakaw",
    english: "walk / trip",
    example_bisaya: "Maglakaw ta padulong opisina.",
    example_english: "Let’s walk to the office.",
  },
  {
    bisaya: "dalan",
    english: "road / street",
    example_bisaya: "Daghan sakyanan sa dalan.",
    example_english: "There are many cars on the road.",
  },
  {
    bisaya: "sakyanan",
    english: "vehicle / car",
    example_bisaya: "Bag-o iyang sakyanan.",
    example_english: "His car is new.",
  },
  {
    bisaya: "bus",
    english: "bus",
    example_bisaya: "Miabot na ang bus.",
    example_english: "The bus has arrived.",
  },
  {
    bisaya: "jeep",
    english: "jeepney",
    example_bisaya: "Sakay ta sa jeep.",
    example_english: "Let’s ride the jeepney.",
  },
  {
    bisaya: "pliti",
    english: "fare",
    example_bisaya: "Tagpila ang pliti?",
    example_english: "How much is the fare?",
  },
  {
    bisaya: "orasanan",
    english: "schedule / timetable",
    example_bisaya: "Unsay orasanan sa bus?",
    example_english: "What’s the bus schedule?",
  },
  {
    bisaya: "gutom",
    english: "hunger",
    example_bisaya: "Gutom na ko.",
    example_english: "I’m already hungry.",
  },
  {
    bisaya: "kapoy",
    english: "tiredness / fatigue",
    example_bisaya: "Kapoy ko gikan trabaho.",
    example_english: "I’m tired from work.",
  },
  {
    bisaya: "pahulay",
    english: "rest",
    example_bisaya: "Magpahulay sa ta gamay.",
    example_english: "Let’s rest for a bit.",
  },
];
