export const Nouns = [
  {
    bisaya: "tawo",
    english: "person / people",
    example_bisaya: "Daghang tawo sa plaza.",
    example_english: "There are many people in the plaza.",
  },
  {
    bisaya: "bata",
    english: "child",
    example_bisaya: "Ang bata nagdula sa gawas.",
    example_english: "The child is playing outside.",
  },
  {
    bisaya: "pamilya",
    english: "family",
    example_bisaya: "Gusto ko nga magkauban ang pamilya sa pista.",
    example_english: "I want to be with my family at the fiesta.",
  },
  {
    bisaya: "mama",
    english: "mother",
    example_bisaya: "Si Mama nagluto sa kusina.",
    example_english: "Mom is cooking in the kitchen.",
  },
  {
    bisaya: "papa",
    english: "father",
    example_bisaya: "Si Papa nagtrabaho sa opisina.",
    example_english: "Dad is working at the office.",
  },
  {
    bisaya: "amigo",
    english: "friend (male)",
    example_bisaya: "Ang akong amigo motabang nako.",
    example_english: "My male friend will help me.",
  },
  {
    bisaya: "amiga",
    english: "friend (female)",
    example_bisaya: "Adto ko sa balay sa akong amiga.",
    example_english: "I will go to my female friend’s house.",
  },
  {
    bisaya: "balay",
    english: "house",
    example_bisaya: "Ang balay kay dako ug puti.",
    example_english: "The house is big and white.",
  },
  {
    bisaya: "kwarto",
    english: "room / bedroom",
    example_bisaya: "Nagpahuway siya sa iyang kwarto.",
    example_english: "He is resting in his bedroom.",
  },
  {
    bisaya: "kusina",
    english: "kitchen",
    example_bisaya: "Naay pagkaon sa kusina.",
    example_english: "There is food in the kitchen.",
  },
  {
    bisaya: "sala",
    english: "living room",
    example_bisaya: "Naglingkod sila sa sala.",
    example_english: "They are sitting in the living room.",
  },
  {
    bisaya: "banyo",
    english: "bathroom",
    example_bisaya: "Gamiton nako ang banyo.",
    example_english: "I will use the bathroom.",
  },
  {
    bisaya: "eskwela",
    english: "school",
    example_bisaya: "Ang mga bata nag-eskwela kada buntag.",
    example_english: "The children go to school every morning.",
  },
  {
    bisaya: "klase",
    english: "class",
    example_bisaya: "Sugdan na ang klase.",
    example_english: "The class is starting now.",
  },
  {
    bisaya: "trabaho",
    english: "work / job",
    example_bisaya: "Daghan kog trabaho karon.",
    example_english: "I have a lot of work today.",
  },
  {
    bisaya: "opisina",
    english: "office",
    example_bisaya: "Siya nagtrabaho sa opisina.",
    example_english: "He works in the office.",
  },
  {
    bisaya: "merkado",
    english: "market",
    example_bisaya: "Mamalit ta sa merkado ug isda.",
    example_english: "Let’s buy fish at the market.",
  },
  {
    bisaya: "tindahan",
    english: "store",
    example_bisaya: "Palit kog tinapay sa tindahan.",
    example_english: "I’ll buy bread at the store.",
  },
  {
    bisaya: "pagkaon",
    english: "food",
    example_bisaya: "Lami ang pagkaon sa fiesta.",
    example_english: "The food at the fiesta is delicious.",
  },
  {
    bisaya: "tubig",
    english: "water",
    example_bisaya: "Mangayo kog usa ka baso nga tubig.",
    example_english: "I will ask for a glass of water.",
  },
  {
    bisaya: "isda",
    english: "fish",
    example_bisaya: "Nagluto si Mama ug isda.",
    example_english: "Mom cooked fish.",
  },
  {
    bisaya: "manok",
    english: "chicken",
    example_bisaya: "Ang manok nagdagan sa nataran.",
    example_english: "The chicken ran in the yard.",
  },
  {
    bisaya: "baboy",
    english: "pig / pork",
    example_bisaya: "Nag-ihaw sila ug baboy sa fiesta.",
    example_english: "They roasted a pig at the fiesta.",
  },
  {
    bisaya: "prutas",
    english: "fruit",
    example_bisaya: "Ganahan ko mokaon ug prutas.",
    example_english: "I like to eat fruit.",
  },
  {
    bisaya: "gulay",
    english: "vegetable",
    example_bisaya: "Ang gulay maayo para sa lawas.",
    example_english: "Vegetables are good for the body.",
  },
  {
    bisaya: "kwarta",
    english: "money",
    example_bisaya: "Wala koy igong kwarta.",
    example_english: "I don’t have enough money.",
  },
  {
    bisaya: "oras",
    english: "time / hour",
    example_bisaya: "Unsa na nga oras?",
    example_english: "What time is it?",
  },
  {
    bisaya: "adlaw",
    english: "day / sun",
    example_bisaya: "Init ang adlaw karon.",
    example_english: "The sun is hot today.",
  },
  {
    bisaya: "gabi-i",
    english: "night",
    example_bisaya: "Maayong gabi-i, Mama.",
    example_english: "Good evening, Mom.",
  },
  {
    bisaya: "buntag",
    english: "morning",
    example_bisaya: "Maayong buntag, Papa.",
    example_english: "Good morning, Dad.",
  },
  {
    bisaya: "hapon",
    english: "afternoon",
    example_bisaya: "Maayong hapon sa tanan.",
    example_english: "Good afternoon to everyone.",
  },
  {
    bisaya: "bulan",
    english: "month / moon",
    example_bisaya: "Ang bulan nindot tan-awon.",
    example_english: "The moon looks beautiful.",
  },
  {
    bisaya: "tuig",
    english: "year",
    example_bisaya: "Bag-ong tuig na ugma.",
    example_english: "It’s New Year tomorrow.",
  },
  {
    bisaya: "sakyanan",
    english: "vehicle / car",
    example_bisaya: "Bag-o ang ilang sakyanan.",
    example_english: "Their car is new.",
  },
  {
    bisaya: "eroplano",
    english: "airplane",
    example_bisaya: "Mosakay mi ug eroplano padulong Manila.",
    example_english: "We will ride a plane to Manila.",
  },
  {
    bisaya: "barko",
    english: "ship",
    example_bisaya: "Ang barko modunggo sa pier.",
    example_english: "The ship will dock at the pier.",
  },
  {
    bisaya: "libro",
    english: "book",
    example_bisaya: "Nagbasa siya ug libro.",
    example_english: "She is reading a book.",
  },
  {
    bisaya: "lapis",
    english: "pencil",
    example_bisaya: "Manghulam kog lapis.",
    example_english: "I will borrow a pencil.",
  },
  {
    bisaya: "papel",
    english: "paper",
    example_bisaya: "Isulat sa papel ang imong ngalan.",
    example_english: "Write your name on the paper.",
  },
  {
    bisaya: "telebisyon",
    english: "television",
    example_bisaya: "Naglantaw sila ug salida sa telebisyon.",
    example_english: "They are watching a show on the television.",
  },
  {
    bisaya: "radyo",
    english: "radio",
    example_bisaya: "Nagpaminaw siya sa radyo.",
    example_english: "He is listening to the radio.",
  },
  {
    bisaya: "suga",
    english: "light / lamp",
    example_bisaya: "Palihug pawala ang suga.",
    example_english: "Please turn off the light.",
  },
  {
    bisaya: "orasan",
    english: "clock",
    example_bisaya: "Ang orasan nagpakita ug alas dose.",
    example_english: "The clock shows twelve o’clock.",
  },
  {
    bisaya: "habol",
    english: "blanket",
    example_bisaya: "Gamiton nako ang habol kay tugnaw.",
    example_english: "I’ll use the blanket because it’s cold.",
  },
  {
    bisaya: "unlan",
    english: "pillow",
    example_bisaya: "Butangi ug unlan ang ulo.",
    example_english: "Put a pillow under your head.",
  },
  {
    bisaya: "aparador",
    english: "cabinet / wardrobe",
    example_bisaya: "Naay sinina sa aparador.",
    example_english: "There are clothes in the wardrobe.",
  },
  {
    bisaya: "bintana",
    english: "window",
    example_bisaya: "Ablihi ang bintana aron makasulod ang hangin.",
    example_english: "Open the window so air can come in.",
  },
  {
    bisaya: "pultahan",
    english: "door",
    example_bisaya: "Sirado ang pultahan.",
    example_english: "The door is closed.",
  },
  {
    bisaya: "plaza",
    english: "town plaza",
    example_bisaya: "Magkita ta sa plaza ugma.",
    example_english: "Let’s meet at the town plaza tomorrow.",
  },
  {
    bisaya: "dalan",
    english: "road / street",
    example_bisaya: "Daghan sakyanan sa dalan.",
    example_english: "There are many vehicles on the street.",
  },
  {
    bisaya: "basura",
    english: "trash",
    example_bisaya: "Ilabay ang basura sa basurahan.",
    example_english: "Throw the trash in the bin.",
  },
  {
    bisaya: "simbahan",
    english: "church",
    example_bisaya: "Mosimba ta sa simbahan dominggo.",
    example_english: "We will go to church on Sunday.",
  },
];
