export const Other = [
  {
    bisaya: "ako",
    english: "I / me",
    example_bisaya: "Ako si Daniel.",
    example_english: "I am Daniel.",
  },
  {
    bisaya: "ikaw",
    english: "you (singular)",
    example_bisaya: "Ikaw ba ang akong amigo?",
    example_english: "Are you my friend?",
  },
  {
    bisaya: "siya",
    english: "he / she / him / her",
    example_bisaya: "Siya ang akong igsoon.",
    example_english: "He/She is my sibling.",
  },
  {
    bisaya: "kami",
    english: "we (exclusive)",
    example_bisaya: "Kami ra ang moadto.",
    example_english: "Only we will go.",
  },
  {
    bisaya: "kita",
    english: "we (inclusive)",
    example_bisaya: "Kita magkuyog ugma.",
    example_english: "We will go together tomorrow.",
  },
  {
    bisaya: "sila",
    english: "they / them",
    example_bisaya: "Sila ang mga bisita.",
    example_english: "They are the visitors.",
  },
  {
    bisaya: "kaniya",
    english: "to him / her",
    example_bisaya: "Ihatag kini kaniya.",
    example_english: "Give this to him/her.",
  },
  {
    bisaya: "kaniadto",
    english: "before / formerly",
    example_bisaya: "Kaniadto siya nagpuyo sa Cebu.",
    example_english: "Before, he/she lived in Cebu.",
  },
  {
    bisaya: "sa",
    english: "in / on / at / to",
    example_bisaya: "Naa siya sa balay.",
    example_english: "He/She is at home.",
  },
  {
    bisaya: "ug",
    english: "and",
    example_bisaya: "Ako ug ikaw magdula.",
    example_english: "You and I will play.",
  },
  {
    bisaya: "apan",
    english: "but",
    example_bisaya: "Gusto ko mokaon apan busog na ko.",
    example_english: "I want to eat but I am full.",
  },
  {
    bisaya: "o",
    english: "or",
    example_bisaya: "Tubig o juice imong gusto?",
    example_english: "Do you want water or juice?",
  },
  {
    bisaya: "kay",
    english: "because / for",
    example_bisaya: "Dili siya moadto kay kapoy siya.",
    example_english: "He/She won’t go because he/she is tired.",
  },
  {
    bisaya: "busa",
    english: "so / therefore",
    example_bisaya: "Wala siya nakastudy, busa bagsak siya.",
    example_english: "He/She didn’t study, so he/she failed.",
  },
  {
    bisaya: "dili",
    english: "not / no",
    example_bisaya: "Dili ko gusto mokaon.",
    example_english: "I do not want to eat.",
  },
  {
    bisaya: "oo",
    english: "yes",
    example_bisaya: "Oo, gusto ko ana.",
    example_english: "Yes, I like that.",
  },
  {
    bisaya: "ngano",
    english: "why",
    example_bisaya: "Ngano naulahi ka?",
    example_english: "Why are you late?",
  },
  {
    bisaya: "unsa",
    english: "what",
    example_bisaya: "Unsa imong pangalan?",
    example_english: "What is your name?",
  },
  {
    bisaya: "asa",
    english: "where",
    example_bisaya: "Asa ka paingon?",
    example_english: "Where are you going?",
  },
  {
    bisaya: "kanus-a",
    english: "when",
    example_bisaya: "Kanus-a siya moabot?",
    example_english: "When will he/she arrive?",
  },
  {
    bisaya: "giunsa",
    english: "how",
    example_bisaya: "Giunsa nimo paghimo niini?",
    example_english: "How did you do this?",
  },
  {
    bisaya: "kinsa",
    english: "who",
    example_bisaya: "Kinsa siya?",
    example_english: "Who is he/she?",
  },
  {
    bisaya: "pila",
    english: "how many / how much",
    example_bisaya: "Pila ang presyo?",
    example_english: "How much is the price?",
  },
  {
    bisaya: "karon",
    english: "now",
    example_bisaya: "Karon siya moadto.",
    example_english: "He/She will go now.",
  },
  {
    bisaya: "unya",
    english: "later / next",
    example_bisaya: "Unya ta magkita.",
    example_english: "We will meet later.",
  },
  {
    bisaya: "ugma",
    english: "tomorrow",
    example_bisaya: "Ugma ang akong adlawng natawhan.",
    example_english: "Tomorrow is my birthday.",
  },
  {
    bisaya: "gahapon",
    english: "yesterday",
    example_bisaya: "Nakita tika gahapon.",
    example_english: "I saw you yesterday.",
  },
  {
    bisaya: "kanunay",
    english: "always",
    example_bisaya: "Kanunay siya nag-ampo.",
    example_english: "He/She always prays.",
  },
  {
    bisaya: "usahay",
    english: "sometimes",
    example_bisaya: "Usahay siya malipayon.",
    example_english: "Sometimes he/she is happy.",
  },
  {
    bisaya: "permi",
    english: "constantly / often",
    example_bisaya: "Permi siya malate.",
    example_english: "He/She is often late.",
  },
  {
    bisaya: "hinay",
    english: "slowly / gently",
    example_bisaya: "Paglakaw og hinay.",
    example_english: "Walk slowly.",
  },
  {
    bisaya: "dali",
    english: "quickly / fast",
    example_bisaya: "Dali pagdagan!",
    example_english: "Run fast!",
  },
  {
    bisaya: "sa ibabaw",
    english: "on top / above",
    example_bisaya: "Naa sa ibabaw ang libro.",
    example_english: "The book is on top.",
  },
  {
    bisaya: "ilawom",
    english: "under / below",
    example_bisaya: "Naa sa ilawom ang bola.",
    example_english: "The ball is under.",
  },
  {
    bisaya: "taliwala sa",
    english: "between / among",
    example_bisaya: "Taliwala sa duha ka lingkoranan siya nagpungko.",
    example_english: "He/She sat between two chairs.",
  },
  {
    bisaya: "atbang sa",
    english: "in front of / opposite",
    example_bisaya: "Naa siya atbang sa simbahan.",
    example_english: "He/She is in front of the church.",
  },
  {
    bisaya: "duol sa",
    english: "near / close to",
    example_bisaya: "Ang eskwelahan duol sa merkado.",
    example_english: "The school is near the market.",
  },
  {
    bisaya: "luyo sa",
    english: "behind / at the back of",
    example_bisaya: "Ang aso naa sa luyo sa balay.",
    example_english: "The smoke is behind the house.",
  },
  {
    bisaya: "sa kilid sa",
    english: "beside / next to",
    example_bisaya: "Naa siya sa kilid sa akong higala.",
    example_english: "He/She is beside my friend.",
  },
  {
    bisaya: "usa",
    english: "one",
    example_bisaya: "Usa ka libro.",
    example_english: "One book.",
  },
  {
    bisaya: "duha",
    english: "two",
    example_bisaya: "Duha ka saging.",
    example_english: "Two bananas.",
  },
  {
    bisaya: "tulo",
    english: "three",
    example_bisaya: "Tulo ka bata.",
    example_english: "Three children.",
  },
  {
    bisaya: "upat",
    english: "four",
    example_bisaya: "Upat ka pinggan.",
    example_english: "Four plates.",
  },
  {
    bisaya: "lima",
    english: "five",
    example_bisaya: "Lima ka libro.",
    example_english: "Five books.",
  },
  {
    bisaya: "unom",
    english: "six",
    example_bisaya: "Unom ka tawo.",
    example_english: "Six people.",
  },
  {
    bisaya: "pito",
    english: "seven",
    example_bisaya: "Pito ka lingkuranan.",
    example_english: "Seven chairs.",
  },
  {
    bisaya: "walo",
    english: "eight",
    example_bisaya: "Walo ka bulak.",
    example_english: "Eight flowers.",
  },
  {
    bisaya: "siyam",
    english: "nine",
    example_bisaya: "Siyam ka libro.",
    example_english: "Nine books.",
  },
  {
    bisaya: "napulo",
    english: "ten",
    example_bisaya: "Napulo ka itlog.",
    example_english: "Ten eggs.",
  },
  {
    bisaya: "kaniadto",
    english: "before / formerly",
    example_bisaya: "Kaniadto, wala pa'y internet.",
    example_english: "Before, there was no internet.",
  },
  {
    bisaya: "kaniya",
    english: "to him / her",
    example_bisaya: "Ihatag kini kaniya.",
    example_english: "Give this to him/her.",
  },
  {
    bisaya: "sa",
    english: "in / on / at / to",
    example_bisaya: "Sa balay ko magpahuway.",
    example_english: "I will rest at home.",
  },
  {
    bisaya: "apan",
    english: "but",
    example_bisaya: "Gusto ko mokaon apan busog na ko.",
    example_english: "I want to eat but I am full.",
  },
  {
    bisaya: "o",
    english: "or",
    example_bisaya: "Kape o tsaa?",
    example_english: "Coffee or tea?",
  },
  {
    bisaya: "kay",
    english: "because / for",
    example_bisaya: "Dili siya moadto kay kapoy siya.",
    example_english: "He won’t go because he is tired.",
  },
  {
    bisaya: "busa",
    english: "so / therefore",
    example_bisaya: "Uwanon, busa magdala kog payong.",
    example_english: "It will rain, so I’ll bring an umbrella.",
  },
  {
    bisaya: "oo",
    english: "yes",
    example_bisaya: "Oo, mouban ko.",
    example_english: "Yes, I will come along.",
  },
  {
    bisaya: "ugma pa",
    english: "later / tomorrow",
    example_bisaya: "Ugma pa ko mubuhat sa proyekto.",
    example_english: "I’ll work on the project tomorrow.",
  },
  {
    bisaya: "kaniadto pa",
    english: "long ago / formerly",
    example_bisaya: "Kaniadto pa siya nagpuyo dinhi.",
    example_english: "He has lived here since long ago.",
  },
  {
    bisaya: "sa sunod",
    english: "next / following",
    example_bisaya: "Sa sunod semana ta magkita.",
    example_english: "We’ll meet next week.",
  },
  {
    bisaya: "sa wala pa",
    english: "before",
    example_bisaya: "Pag-andam sa wala pa magsugod.",
    example_english: "Prepare before it starts.",
  },
  {
    bisaya: "una",
    english: "first / before",
    example_bisaya: "Ikaw una mokaon.",
    example_english: "You eat first.",
  },
  {
    bisaya: "ikaduha",
    english: "second",
    example_bisaya: "Ikaduha siya sa linya.",
    example_english: "He is second in line.",
  },
  {
    bisaya: "ikatulo",
    english: "third",
    example_bisaya: "Ikatulo nako nga higayon ning bisitaha.",
    example_english: "This is my third visit.",
  },
  {
    bisaya: "ikasiyam",
    english: "ninth",
    example_bisaya: "Siya ang ikasiyam nga estudyante.",
    example_english: "He is the ninth student.",
  },
  {
    bisaya: "ikapulo",
    english: "tenth",
    example_bisaya: "Ikatapusan siya kay ikapulo siya.",
    example_english: "He was last because he was tenth.",
  },
  {
    bisaya: "alang kanimo",
    english: "for you",
    example_bisaya: "Kini alang kanimo.",
    example_english: "This is for you.",
  },
  {
    bisaya: "alang kanila",
    english: "for them",
    example_bisaya: "Ang tabang alang kanila.",
    example_english: "The help is for them.",
  },
  {
    bisaya: "alang kanamo",
    english: "for us",
    example_bisaya: "Ang regalo alang kanamo.",
    example_english: "The gift is for us.",
  },
  {
    bisaya: "alang sa tanan",
    english: "for everyone",
    example_bisaya: "Libre kini alang sa tanan.",
    example_english: "This is free for everyone.",
  },
  {
    bisaya: "uban kanila",
    english: "with them",
    example_bisaya: "Naglakaw siya uban kanila.",
    example_english: "He walked with them.",
  },
  {
    bisaya: "uban kanimo",
    english: "with you",
    example_bisaya: "Mosayaw ko uban kanimo.",
    example_english: "I will dance with you.",
  },
  {
    bisaya: "uban kanamo",
    english: "with us",
    example_bisaya: "Pagdula uban kanamo.",
    example_english: "Play with us.",
  },
  {
    bisaya: "hangtod",
    english: "until / up to",
    example_bisaya: "Maghulat ko hangtod moabot ka.",
    example_english: "I’ll wait until you arrive.",
  },
  {
    bisaya: "sa wala",
    english: "before / not yet",
    example_bisaya: "Sa wala ko molakaw, mokaon sa ko.",
    example_english: "Before I leave, I’ll eat first.",
  },
  {
    bisaya: "karon ra",
    english: "just now / currently",
    example_bisaya: "Karon ra siya miabot.",
    example_english: "He just arrived.",
  },
  {
    bisaya: "sa kanunay",
    english: "always / constantly",
    example_bisaya: "Nag-ampo siya sa kanunay.",
    example_english: "He prays constantly.",
  },
  {
    bisaya: "sa usahay",
    english: "sometimes",
    example_bisaya: "Sa usahay ra ko mokaon ug ice cream.",
    example_english: "I only eat ice cream sometimes.",
  },
  {
    bisaya: "daghan pa",
    english: "more / many more",
    example_bisaya: "Daghan pa ang hulat.",
    example_english: "There are many more waiting.",
  },
  {
    bisaya: "gamay ra",
    english: "just a few / small amount",
    example_bisaya: "Gamay ra ang akong kwarta.",
    example_english: "I only have a small amount of money.",
  },
  {
    bisaya: "paspas",
    english: "fast / quickly",
    example_bisaya: "Paspas siya modagan.",
    example_english: "He runs fast.",
  },
  {
    bisaya: "hinay-hinay",
    english: "slowly / gently",
    example_bisaya: "Hinay-hinay lang sa paglakaw.",
    example_english: "Walk slowly.",
  },
  {
    bisaya: "pinakamaayo",
    english: "the best",
    example_bisaya: "Ikaw ang pinakamaayo nga magdula.",
    example_english: "You are the best player.",
  },
  {
    bisaya: "pinakagrabe",
    english: "the worst / most extreme",
    example_bisaya: "Kini ang pinakagrabe nga bagyo.",
    example_english: "This is the worst storm.",
  },
];
