export const Verbs = [
  {
    bisaya: "adto",
    english: "to go (there)",
    example_bisaya: "Adto ko sa merkado.",
    example_english: "I will go to the market.",
  },
  {
    bisaya: "anhi",
    english: "to come (here)",
    example_bisaya: "Anhi diri sa balay.",
    example_english: "Come here to the house.",
  },
  {
    bisaya: "balik",
    english: "to return / come back",
    example_bisaya: "Mobalik siya ugma.",
    example_english: "He will come back tomorrow.",
  },
  {
    bisaya: "tan-aw",
    english: "to look / watch",
    example_bisaya: "Tan-awa ang salida.",
    example_english: "Watch the movie.",
  },
  {
    bisaya: "pamati",
    english: "to listen / feel",
    example_bisaya: "Pamati sa akong giingon.",
    example_english: "Listen to what I said.",
  },
  {
    bisaya: "dungog",
    english: "to hear",
    example_bisaya: "Nadungog nako ang tingog.",
    example_english: "I heard the voice.",
  },
  {
    bisaya: "kaon",
    english: "to eat",
    example_bisaya: "Mokaon ta ug pan.",
    example_english: "Let’s eat bread.",
  },
  {
    bisaya: "inom",
    english: "to drink",
    example_bisaya: "Mu-inom siya ug tubig.",
    example_english: "She will drink water.",
  },
  {
    bisaya: "luto",
    english: "to cook",
    example_bisaya: "Nag-luto siya ug isda.",
    example_english: "He is cooking fish.",
  },
  {
    bisaya: "palit",
    english: "to buy",
    example_bisaya: "Mopalit ko ug prutas.",
    example_english: "I will buy fruits.",
  },
  {
    bisaya: "baligya",
    english: "to sell",
    example_bisaya: "Iyang ibaligya ang sakyanan.",
    example_english: "He will sell the car.",
  },
  {
    bisaya: "kuha",
    english: "to take / get",
    example_bisaya: "Kuhaa ang libro.",
    example_english: "Get the book.",
  },
  {
    bisaya: "hatag",
    english: "to give",
    example_bisaya: "Ihatag nako ang regalo.",
    example_english: "I will give the gift.",
  },
  {
    bisaya: "dala",
    english: "to bring / carry",
    example_bisaya: "Dala ug payong.",
    example_english: "Bring an umbrella.",
  },
  {
    bisaya: "buhat",
    english: "to do / make",
    example_bisaya: "Unsay imong buhaton?",
    example_english: "What will you do?",
  },
  {
    bisaya: "trabaho",
    english: "to work",
    example_bisaya: "Nagtrabaho siya sa opisina.",
    example_english: "She works in the office.",
  },
  {
    bisaya: "tuon",
    english: "to study / learn",
    example_bisaya: "Nagtuon siya sa klase.",
    example_english: "He is studying in class.",
  },
  {
    bisaya: "basa",
    english: "to read",
    example_bisaya: "Basaha ang libro.",
    example_english: "Read the book.",
  },
  {
    bisaya: "sulat",
    english: "to write",
    example_bisaya: "Nagsulat siya ug liham.",
    example_english: "She wrote a letter.",
  },
  {
    bisaya: "lakaw",
    english: "to walk / leave",
    example_bisaya: "Molakaw mi padulong sa simbahan.",
    example_english: "We will walk to the church.",
  },
  {
    bisaya: "dagan",
    english: "to run",
    example_bisaya: "Nidagan siya sa dalan.",
    example_english: "He ran on the street.",
  },
  {
    bisaya: "langoy",
    english: "to swim",
    example_bisaya: "Molangoy sila sa dagat.",
    example_english: "They will swim in the sea.",
  },
  {
    bisaya: "ambak",
    english: "to jump",
    example_bisaya: "Ambak sa taas nga bato.",
    example_english: "Jump on the big rock.",
  },
  {
    bisaya: "lingkod",
    english: "to sit",
    example_bisaya: "Lingkod sa bangko.",
    example_english: "Sit on the bench.",
  },
  {
    bisaya: "barug",
    english: "to stand",
    example_bisaya: "Pagbarug sa lamesa.",
    example_english: "Stand by the table.",
  },
  {
    bisaya: "higda",
    english: "to lie down",
    example_bisaya: "Higda sa higdaanan.",
    example_english: "Lie down on the bed.",
  },
  {
    bisaya: "tulog",
    english: "to sleep",
    example_bisaya: "Matulog siya karon.",
    example_english: "He will sleep now.",
  },
  {
    bisaya: "mata",
    english: "to wake up",
    example_bisaya: "Namata siya sayo.",
    example_english: "She woke up early.",
  },
  {
    bisaya: "panilhig",
    english: "to sweep",
    example_bisaya: "Panilhiga ang sala.",
    example_english: "Sweep the living room.",
  },
  {
    bisaya: "labay",
    english: "to throw away",
    example_bisaya: "Ilabay ang basura.",
    example_english: "Throw away the trash.",
  },
  {
    bisaya: "tanom",
    english: "to plant",
    example_bisaya: "Nagtanom siya ug bulak.",
    example_english: "She planted flowers.",
  },
  {
    bisaya: "abli",
    english: "to open",
    example_bisaya: "Ablihi ang pultahan.",
    example_english: "Open the door.",
  },
  {
    bisaya: "sirado",
    english: "to close",
    example_bisaya: "Siradi ang bintana.",
    example_english: "Close the window.",
  },
  {
    bisaya: "adtoon",
    english: "to visit",
    example_bisaya: "Amo siyang adtoon ugma.",
    example_english: "We will visit him tomorrow.",
  },
  {
    bisaya: "gamit",
    english: "to use",
    example_bisaya: "Gigamit nako ang cellphone.",
    example_english: "I used the cellphone.",
  },
  {
    bisaya: "tan-awon",
    english: "to watch / observe",
    example_bisaya: "Tan-awon nako ang salida.",
    example_english: "I will watch the show.",
  },
  {
    bisaya: "kanta",
    english: "to sing",
    example_bisaya: "Makanta siya ug bisaya nga awit.",
    example_english: "She can sing a Bisaya song.",
  },
  {
    bisaya: "sayaw",
    english: "to dance",
    example_bisaya: "Misayaw sila sa pista.",
    example_english: "They danced at the fiesta.",
  },
  {
    bisaya: "dula",
    english: "to play",
    example_bisaya: "Nagduwa ang mga bata.",
    example_english: "The kids are playing.",
  },
  {
    bisaya: "suroy",
    english: "to stroll / hang out",
    example_bisaya: "Mag-suroy ta sa plaza.",
    example_english: "Let’s stroll around the plaza.",
  },
  {
    bisaya: "tabang",
    english: "to help",
    example_bisaya: "Tabangi ko palihug.",
    example_english: "Help me please.",
  },
  {
    bisaya: "ampo",
    english: "to pray",
    example_bisaya: "Nag-ampo siya matag adlaw.",
    example_english: "She prays every day.",
  },
  {
    bisaya: "katawa",
    english: "to laugh",
    example_bisaya: "Nangatawa sila sa joke.",
    example_english: "They laughed at the joke.",
  },
  {
    bisaya: "hilak",
    english: "to cry",
    example_bisaya: "Nihilak ang bata.",
    example_english: "The child cried.",
  },
  {
    bisaya: "hunahuna",
    english: "to think",
    example_bisaya: "Naghunahuna siya ug solusyon.",
    example_english: "He is thinking of a solution.",
  },
  {
    bisaya: "istorya",
    english: "to talk / speak",
    example_bisaya: "Nag-istorya sila sa tindahan.",
    example_english: "They are talking at the store.",
  },
  {
    bisaya: "sulti",
    english: "to say / tell",
    example_bisaya: "Isulti ang imong pangalan.",
    example_english: "Say your name.",
  },
];
